from __future__ import annotations

from io import BytesIO

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from phageai_core import Phage, Query, rank_phages
from pydantic import BaseModel
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


class CandidateIn(BaseModel):
    id: str
    name: str
    host_species: str
    lifecycle: str | None = None
    source_url: str | None = None


class RankRequest(BaseModel):
    host_species: str
    candidates: list[CandidateIn]


class RankedResultIn(BaseModel):
    id: str
    name: str
    host_species: str
    lifecycle: str | None = None
    source_url: str | None = None
    score: int
    reasons_json: dict


class ExportFiltersIn(BaseModel):
    lyticOnly: bool | None = None
    minScore: float | None = None


class ExportPdfRequest(BaseModel):
    host_species: str
    filters: ExportFiltersIn
    results: list[RankedResultIn]


app = FastAPI(title="PhageAI Match API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health() -> dict[str, bool]:
    return {"ok": True}


@app.post("/rank")
def rank(payload: RankRequest) -> list[dict]:
    ranked = rank_phages(
        Query(host_species=payload.host_species),
        [Phage(**candidate.model_dump()) for candidate in payload.candidates],
    )
    return [
        {
            "id": phage.id,
            "name": phage.name,
            "host_species": phage.host_species,
            "lifecycle": phage.lifecycle,
            "source_url": phage.source_url,
            "score": phage.score,
            "reasons_json": phage.reasons_json,
        }
        for phage in ranked
    ]


@app.post("/export/pdf")
def export_pdf(payload: ExportPdfRequest) -> Response:
    buffer = BytesIO()
    document = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()

    top_results = payload.results[:50]
    summary = (
        f"Total results: {len(payload.results)} | "
        f"Filters: lyticOnly={bool(payload.filters.lyticOnly)}, "
        f"minScore={payload.filters.minScore if payload.filters.minScore is not None else 0}"
    )

    story = [
        Paragraph("PhageAI Match Report", styles["Title"]),
        Spacer(1, 8),
        Paragraph(f"Host: {payload.host_species}", styles["Normal"]),
        Spacer(1, 4),
        Paragraph(summary, styles["Normal"]),
        Spacer(1, 12),
    ]

    table_data = [["Name / ID", "Score", "Lifecycle", "Host", "Source URL"]]
    for item in top_results:
        table_data.append(
            [
                f"{item.name} / {item.id}",
                str(item.score),
                item.lifecycle or "",
                item.host_species,
                item.source_url or "",
            ]
        )

    table = Table(table_data, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(table)
    story.extend(
        [
            Spacer(1, 12),
            Paragraph(
                "Disclaimer: This report is generated by heuristic ranking and should be used "
                "for research triage only.",
                styles["Italic"],
            ),
        ]
    )

    document.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return Response(content=pdf_bytes, media_type="application/pdf")
